export const COLLECTION_RARITIES = [
  'Common',
  'Rare',
  'Epic',
  'Legendary',
  'Mythic',
];

export const COLLECTION_CATEGORIES = {
  pieceSet: 'piece-set',
  pieceTheme: 'piece-theme',
  boardTheme: 'board-theme',
  badge: 'badge',
  profileFrame: 'profile-frame',
  rushResultFrame: 'rush-result-frame',
  comboEffect: 'combo-effect',
};

export const PIECE_TYPES = [
  'Pawn',
  'Knight',
  'Bishop',
  'Rook',
  'Queen',
  'King',
];

export const CHEST_TYPES = [
  {
    id: 'basic-chest',
    name: 'Basic Chest',
    tier: 'Common',
    sources: ['Blitz Rush', 'Daily Rush streaks', 'early Ladder node clears'],
    intendedRewards: ['Common pieces', 'starter badges', 'small cosmetic progress'],
  },
  {
    id: 'tactical-chest',
    name: 'Tactical Chest',
    tier: 'Rare',
    sources: ['Blitz Rush', 'Classic Rush', 'higher rank results'],
    intendedRewards: ['Common pieces', 'Rare pieces', 'tactical badges'],
  },
  {
    id: 'royal-chest',
    name: 'Royal Chest',
    tier: 'Epic',
    sources: ['Classic Rush', 'Survival Rush', 'boss battle wins'],
    intendedRewards: ['Rare pieces', 'Epic pieces', 'Royal Set progress'],
  },
  {
    id: 'survival-chest',
    name: 'Survival Chest',
    tier: 'Epic',
    sources: ['Survival Rush', 'long-run milestones'],
    intendedRewards: ['Rare pieces', 'Epic pieces', 'Shadow Set progress'],
  },
  {
    id: 'legendary-chest',
    name: 'Legendary Chest',
    tier: 'Legendary',
    sources: ['high-rank Survival Rush', 'new best score bonuses', 'Grandmaster Keep milestones'],
    intendedRewards: ['Epic pieces', 'Legendary pieces', 'future Mythic cosmetics'],
  },
];

export const PIECE_THEMES = [
  {
    id: 'classic',
    name: 'Classic',
    rarity: 'Common',
    unlockSource: 'Unlocked by default',
    description: 'Clean tournament-style pieces for maximum readability.',
    preview: 'Classic chess symbols',
    defaultUnlocked: true,
    requiredCollectionItems: [],
    requiredCompletedNodes: [],
  },
  {
    id: 'tournament',
    name: 'Tournament',
    rarity: 'Common',
    unlockSource: 'Defeat the Back Rank Guard or unlock Bronze Rook',
    description: 'Sharper contrast with a polished competition feel.',
    preview: 'Crisp weighted pieces',
    defaultUnlocked: false,
    requiredCollectionItems: ['bronze-rook'],
    requiredCompletedNodes: ['pawn-back-rank-guard'],
  },
  {
    id: 'marble',
    name: 'Marble',
    rarity: 'Rare',
    unlockSource: 'Complete Shadow Set progress or defeat The Diagonal Keeper',
    description: 'Stone-cut pieces with bright highlights and deep shadows.',
    preview: 'Carved marble finish',
    defaultUnlocked: false,
    requiredCollectionItems: ['shadow-bishop'],
    requiredCompletedNodes: ['bishop-diagonal-keeper'],
  },
  {
    id: 'shadow',
    name: 'Shadow',
    rarity: 'Epic',
    unlockSource: 'Defeat The Legendary Board',
    description: 'Dark premium pieces with electric edge highlights.',
    preview: 'Dark tactical glow',
    defaultUnlocked: false,
    requiredCollectionItems: [],
    requiredCompletedNodes: ['legendary-board'],
  },
  {
    id: 'royal',
    name: 'Royal',
    rarity: 'Epic',
    unlockSource: "Defeat The Queen's Trial or unlock Royal Queen",
    description: 'Gold-accented pieces for boss and campaign rewards.',
    preview: 'Royal gold accents',
    defaultUnlocked: false,
    requiredCollectionItems: ['royal-queen'],
    requiredCompletedNodes: ['queen-trial'],
  },
];

export const BOARD_THEMES = [
  {
    id: 'classic-green',
    name: 'Classic Green',
    rarity: 'Common',
    unlockSource: 'Unlocked by default',
    description: 'Readable green and parchment board colors.',
    preview: 'Tournament green',
    defaultUnlocked: true,
    lightSquare: '#e7d8bd',
    darkSquare: '#58745f',
    accentColor: '#d7c088',
    frameClassName: 'classic-green',
    requiredCollectionItems: [],
    requiredCompletedNodes: [],
  },
  {
    id: 'tournament-blue',
    name: 'Tournament Blue',
    rarity: 'Common',
    unlockSource: 'Defeat the Back Rank Guard',
    description: 'Clean blue tournament board with crisp mobile contrast.',
    preview: 'Blue tournament board',
    defaultUnlocked: false,
    lightSquare: '#d8e8f3',
    darkSquare: '#3d6f9c',
    accentColor: '#6fb8ff',
    frameClassName: 'tournament-blue',
    requiredCollectionItems: ['bronze-rook'],
    requiredCompletedNodes: ['pawn-back-rank-guard'],
  },
  {
    id: 'walnut',
    name: 'Walnut',
    rarity: 'Common',
    unlockSource: 'Defeat the Back Rank Guard or unlock Bronze Rook',
    description: 'Warm wood tones for early campaign rewards.',
    preview: 'Warm walnut board',
    defaultUnlocked: false,
    lightSquare: '#d7b98b',
    darkSquare: '#8b5a34',
    accentColor: '#d7b98b',
    frameClassName: 'walnut',
    requiredCollectionItems: ['bronze-rook'],
    requiredCompletedNodes: ['pawn-back-rank-guard'],
  },
  {
    id: 'forest',
    name: 'Forest',
    rarity: 'Rare',
    unlockSource: 'Clear Knight Woods or unlock Bronze Knight',
    description: 'Deep green board for fork trails and tactical traps.',
    preview: 'Knight Woods forest board',
    defaultUnlocked: false,
    lightSquare: '#d5dfbf',
    darkSquare: '#416a49',
    accentColor: '#82c46c',
    frameClassName: 'forest',
    requiredCollectionItems: ['bronze-knight'],
    requiredCompletedNodes: ['knight-smothered-king'],
  },
  {
    id: 'slate',
    name: 'Slate',
    rarity: 'Rare',
    unlockSource: 'Unlock Bronze Knight or clear Knight Woods',
    description: 'Cool tactical board with quiet contrast.',
    preview: 'Blue-gray slate board',
    defaultUnlocked: false,
    lightSquare: '#c8d3d9',
    darkSquare: '#526979',
    accentColor: '#95b7c4',
    frameClassName: 'slate',
    requiredCollectionItems: ['bronze-knight'],
    requiredCompletedNodes: ['knight-smothered-king'],
  },
  {
    id: 'sandstone',
    name: 'Sandstone',
    rarity: 'Rare',
    unlockSource: 'Clear Bishop Tower or unlock Shadow Bishop',
    description: 'Warm stone board for diagonal lines and pin motifs.',
    preview: 'Bishop Tower sandstone board',
    defaultUnlocked: false,
    lightSquare: '#ead7b2',
    darkSquare: '#9a6d45',
    accentColor: '#e2bd72',
    frameClassName: 'sandstone',
    requiredCollectionItems: ['shadow-bishop'],
    requiredCompletedNodes: ['bishop-diagonal-keeper'],
  },
  {
    id: 'fortress-iron',
    name: 'Fortress Iron',
    rarity: 'Epic',
    unlockSource: 'Clear Rook Fortress or unlock Royal Rook',
    description: 'Steel board built for rook files and fortress pressure.',
    preview: 'Rook Fortress iron board',
    defaultUnlocked: false,
    lightSquare: '#ccd1d4',
    darkSquare: '#505c66',
    accentColor: '#b7c1c9',
    frameClassName: 'fortress-iron',
    requiredCollectionItems: ['royal-rook'],
    requiredCompletedNodes: ['rook-fortress-king'],
  },
  {
    id: 'royal-court',
    name: 'Royal Court',
    rarity: 'Epic',
    unlockSource: "Clear Queen's Court or unlock Royal Queen",
    description: 'Regal violet and gold board for coordinated attacks.',
    preview: 'Royal court board',
    defaultUnlocked: false,
    lightSquare: '#e5d5ef',
    darkSquare: '#71509a',
    accentColor: '#f2bd4b',
    frameClassName: 'royal-court',
    requiredCollectionItems: ['royal-queen'],
    requiredCompletedNodes: ['queen-trial'],
  },
  {
    id: 'grandmaster-obsidian',
    name: 'Grandmaster Obsidian',
    rarity: 'Legendary',
    unlockSource: "Clear King's Gate or unlock Royal King",
    description: 'Dark obsidian board for late-campaign king hunts.',
    preview: 'Obsidian endgame board',
    defaultUnlocked: false,
    lightSquare: '#adb6c2',
    darkSquare: '#252b35',
    accentColor: '#20e6d2',
    frameClassName: 'grandmaster-obsidian',
    requiredCollectionItems: ['royal-king'],
    requiredCompletedNodes: ['king-running-king'],
  },
  {
    id: 'marble',
    name: 'Marble',
    rarity: 'Epic',
    unlockSource: 'Defeat The Legendary Board',
    description: 'Pale stone board with premium contrast.',
    preview: 'Polished marble board',
    defaultUnlocked: false,
    lightSquare: '#ece7dc',
    darkSquare: '#8e9296',
    accentColor: '#ece7dc',
    frameClassName: 'marble',
    requiredCollectionItems: [],
    requiredCompletedNodes: ['legendary-board'],
  },
  {
    id: 'midnight',
    name: 'Midnight',
    rarity: 'Legendary',
    unlockSource: 'Defeat The Grandmaster Trial or unlock Grandmaster King',
    description: 'Dark arcade board with teal-gold edge energy.',
    preview: 'Premium midnight board',
    defaultUnlocked: false,
    lightSquare: '#95b7c4',
    darkSquare: '#243645',
    accentColor: '#20e6d2',
    frameClassName: 'midnight',
    requiredCollectionItems: ['grandmaster-king'],
    requiredCompletedNodes: ['grandmaster-trial'],
  },
  {
    id: 'ice-summit',
    name: 'Ice Summit',
    rarity: 'Legendary',
    unlockSource: 'Clear Grandmaster Summit',
    description: 'Glacial blue board for deep forcing-line climbs.',
    preview: 'Grandmaster Summit ice board',
    defaultUnlocked: false,
    lightSquare: '#e0f4f8',
    darkSquare: '#5a8ca4',
    accentColor: '#bff6ff',
    frameClassName: 'ice-summit',
    requiredCollectionItems: [],
    requiredCompletedNodes: ['summit-guardian'],
  },
  {
    id: 'legendary-gold',
    name: 'Legendary Gold',
    rarity: 'Mythic',
    unlockSource: 'Defeat The Legendary Board',
    description: 'Prestige gold board for the final campaign hall.',
    preview: 'Legendary Hall gold board',
    defaultUnlocked: false,
    lightSquare: '#f3df9a',
    darkSquare: '#9b6a20',
    accentColor: '#ffd66e',
    frameClassName: 'legendary-gold',
    requiredCollectionItems: [],
    requiredCompletedNodes: ['legendary-board'],
  },
];

const PIECE_SET_CONFIGS = [
  {
    setId: 'classic-set',
    setName: 'Classic Set',
    rarity: 'Common',
    unlockSource: 'Ladder starter progression',
    cosmeticReward: 'Classic board trim',
  },
  {
    setId: 'bronze-set',
    setName: 'Bronze Set',
    rarity: 'Common',
    unlockSource: 'Pawn Village, Knight Woods, Basic Chests, and Tactical Chests',
    cosmeticReward: 'Bronze profile accent',
  },
  {
    setId: 'shadow-set',
    setName: 'Shadow Set',
    rarity: 'Rare',
    unlockSource: 'Knight Woods, Bishop Tower, Rook Fortress, Tactical Chests, and Survival Chests',
    cosmeticReward: 'Shadow result frame',
  },
  {
    setId: 'royal-set',
    setName: 'Royal Set',
    rarity: 'Epic',
    unlockSource: "Bishop Tower, Rook Fortress, Queen's Court, King's Gate, Royal Chests, and boss battle wins",
    cosmeticReward: 'Royal board theme',
  },
  {
    setId: 'grandmaster-set',
    setName: 'Grandmaster Set',
    rarity: 'Legendary',
    unlockSource: 'Grandmaster Keep boss rewards, Legendary Chests, and major zone completions',
    cosmeticReward: 'Grandmaster title and frame',
  },
];

function slugify(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function buildPieceItem(setConfig, pieceType) {
  const pieceSlug = slugify(pieceType);
  const setSlug = setConfig.setId.replace(/-set$/, '');

  return {
    collectionItemId: `${setSlug}-${pieceSlug}`,
    category: COLLECTION_CATEGORIES.pieceSet,
    setId: setConfig.setId,
    setName: setConfig.setName,
    pieceType,
    rarity: setConfig.rarity,
    displayName: `${setConfig.setName.replace(' Set', '')} ${pieceType}`,
    unlockSource: setConfig.unlockSource,
    cosmeticReward: setConfig.cosmeticReward,
    owned: false,
    unlockedAt: null,
  };
}

export const PIECE_SETS = PIECE_SET_CONFIGS.map((setConfig) => ({
  ...setConfig,
  pieces: PIECE_TYPES.map((pieceType) => buildPieceItem(setConfig, pieceType)),
}));

export const COLLECTION_ITEMS = PIECE_SETS.flatMap((pieceSet) => pieceSet.pieces);
