const eFileRook = {
  fen: '6k1/pppp1ppp/8/8/8/8/PPPP1PPP/4R1K1 w - - 0 1',
  finalMove: 'Re8#',
  waits: ['a3', 'a6', 'b3', 'b6', 'c3', 'c6', 'd3', 'd6', 'f3', 'a5', 'g3', 'b5'],
};

const eFileQueen = {
  fen: '6k1/pppp1ppp/8/8/8/8/PPPP1PPP/4Q1K1 w - - 0 1',
  finalMove: 'Qe8#',
  waits: ['a3', 'a6', 'b3', 'b6', 'c3', 'c6', 'd3', 'd6', 'f3', 'a5', 'g3', 'b5'],
};

const aFileRook = {
  fen: '6k1/1ppp1ppp/8/8/8/8/1PPP1PPP/R5K1 w - - 0 1',
  finalMove: 'Ra8#',
  waits: ['b3', 'b6', 'c3', 'c6', 'd3', 'd6', 'f3', 'b5', 'g3', 'c5', 'h3', 'd5'],
};

const aFileQueen = {
  fen: '6k1/1ppp1ppp/8/8/8/8/1PPP1PPP/Q5K1 w - - 0 1',
  finalMove: 'Qa8#',
  waits: ['b3', 'b6', 'c3', 'c6', 'd3', 'd6', 'f3', 'b5', 'g3', 'c5', 'h3', 'd5'],
};

const knightNet = {
  fen: '6rk/pppp2pp/7N/8/8/8/PPPP2PP/6K1 w - - 0 1',
  finalMove: 'Nf7#',
  waits: ['a3', 'a6', 'b3', 'b6', 'c3', 'c6', 'd3', 'd6', 'g3', 'a5', 'h3', 'b5'],
};

function line(pattern, mateIn) {
  return [...pattern.waits.slice(0, (mateIn - 1) * 2), pattern.finalMove];
}

const DEV_QUALITY_NOTES = [
  'Synthetic development/test puzzle generated from a small repeated pattern set.',
  'Not production-quality puzzle content.',
];

// Production puzzle imports must be quality-gated before contentStatus changes
// from "dev": verify no faster mate than claimed, a realistic forcing line,
// varied themes, no repetitive queen/rook-only pattern, and suitable mode fit
// for rush, daily, ladder, or challenge. Rush-fit content should use mateIn,
// difficulty, and rating metadata to scale from quick mates to deeper forced
// mate sequences as the player advances.
function puzzle({
  id,
  title,
  pattern,
  mateIn,
  difficulty,
  rating,
  theme,
  themes = theme,
  contentStatus = 'dev',
  modeFit = ['rush', 'daily', 'ladder'],
  qualityNotes = DEV_QUALITY_NOTES,
  source = 'synthetic-dev-pack-v1',
}) {
  return {
    id,
    title,
    fen: pattern.fen,
    sideToMove: 'white',
    mateIn,
    solution: line(pattern, mateIn),
    difficulty,
    rating,
    theme: themes,
    themes,
    contentStatus,
    modeFit,
    qualityNotes,
    source,
  };
}

const devPuzzles = [
  puzzle({
    id: 'm1-back-rank-rook',
    title: 'Back Rank Rook',
    pattern: eFileRook,
    mateIn: 1,
    difficulty: 'starter',
    rating: 650,
    theme: ['back rank', 'rook'],
  }),
  puzzle({
    id: 'm1-queen-file',
    title: 'Queen on the File',
    pattern: eFileQueen,
    mateIn: 1,
    difficulty: 'starter',
    rating: 700,
    theme: ['back rank', 'queen'],
  }),
  puzzle({
    id: 'm1-corner-rook',
    title: 'Corner Rank Rook',
    pattern: aFileRook,
    mateIn: 1,
    difficulty: 'starter',
    rating: 725,
    theme: ['back rank', 'rook lift'],
  }),
  puzzle({
    id: 'm1-corner-queen',
    title: 'Corner Queen Strike',
    pattern: aFileQueen,
    mateIn: 1,
    difficulty: 'starter',
    rating: 775,
    theme: ['back rank', 'queen'],
  }),
  puzzle({
    id: 'm1-knight-net',
    title: 'Knight Net',
    pattern: knightNet,
    mateIn: 1,
    difficulty: 'starter',
    rating: 825,
    theme: ['knight mate', 'box'],
  }),

  puzzle({
    id: 'm2-file-clearance',
    title: 'File Clearance',
    pattern: eFileRook,
    mateIn: 2,
    difficulty: 'easy',
    rating: 900,
    theme: ['quiet move', 'back rank'],
  }),
  puzzle({
    id: 'm2-queen-wait',
    title: 'Queen Waiting Move',
    pattern: eFileQueen,
    mateIn: 2,
    difficulty: 'easy',
    rating: 950,
    theme: ['tempo', 'queen'],
  }),
  puzzle({
    id: 'm2-rook-corner-net',
    title: 'Rook Corner Net',
    pattern: aFileRook,
    mateIn: 2,
    difficulty: 'easy',
    rating: 980,
    theme: ['tempo', 'rook'],
  }),
  puzzle({
    id: 'm2-queen-corner-net',
    title: 'Queen Corner Net',
    pattern: aFileQueen,
    mateIn: 2,
    difficulty: 'easy',
    rating: 1025,
    theme: ['queen', 'back rank'],
  }),
  puzzle({
    id: 'm2-knight-box',
    title: 'Knight Box',
    pattern: knightNet,
    mateIn: 2,
    difficulty: 'easy',
    rating: 1075,
    theme: ['knight mate', 'tempo'],
  }),

  puzzle({
    id: 'm3-rook-route',
    title: 'Rook Route',
    pattern: eFileRook,
    mateIn: 3,
    difficulty: 'medium',
    rating: 1150,
    theme: ['quiet move', 'back rank'],
  }),
  puzzle({
    id: 'm3-queen-route',
    title: 'Queen Route',
    pattern: eFileQueen,
    mateIn: 3,
    difficulty: 'medium',
    rating: 1200,
    theme: ['queen', 'tempo'],
  }),
  puzzle({
    id: 'm3-a-file-rook',
    title: 'A-File Rook Net',
    pattern: aFileRook,
    mateIn: 3,
    difficulty: 'medium',
    rating: 1240,
    theme: ['rook', 'back rank'],
  }),
  puzzle({
    id: 'm3-a-file-queen',
    title: 'A-File Queen Net',
    pattern: aFileQueen,
    mateIn: 3,
    difficulty: 'medium',
    rating: 1280,
    theme: ['queen', 'back rank'],
  }),
  puzzle({
    id: 'm3-knight-route',
    title: 'Knight Route',
    pattern: knightNet,
    mateIn: 3,
    difficulty: 'medium',
    rating: 1320,
    theme: ['knight mate', 'tempo'],
  }),

  puzzle({
    id: 'm4-rook-ladder',
    title: 'Rook Ladder',
    pattern: eFileRook,
    mateIn: 4,
    difficulty: 'advanced',
    rating: 1400,
    theme: ['back rank', 'calculation'],
  }),
  puzzle({
    id: 'm4-queen-ladder',
    title: 'Queen Ladder',
    pattern: eFileQueen,
    mateIn: 4,
    difficulty: 'advanced',
    rating: 1450,
    theme: ['queen', 'calculation'],
  }),
  puzzle({
    id: 'm4-corner-ladder',
    title: 'Corner Rook Ladder',
    pattern: aFileRook,
    mateIn: 4,
    difficulty: 'advanced',
    rating: 1500,
    theme: ['rook', 'calculation'],
  }),
  puzzle({
    id: 'm4-queen-corner-ladder',
    title: 'Corner Queen Ladder',
    pattern: aFileQueen,
    mateIn: 4,
    difficulty: 'advanced',
    rating: 1540,
    theme: ['queen', 'calculation'],
  }),
  puzzle({
    id: 'm4-knight-ladder',
    title: 'Knight Ladder',
    pattern: knightNet,
    mateIn: 4,
    difficulty: 'advanced',
    rating: 1580,
    theme: ['knight mate', 'calculation'],
  }),

  puzzle({
    id: 'm5-rook-endurance',
    title: 'Rook Endurance',
    pattern: eFileRook,
    mateIn: 5,
    difficulty: 'expert',
    rating: 1680,
    theme: ['back rank', 'endurance'],
  }),
  puzzle({
    id: 'm5-queen-endurance',
    title: 'Queen Endurance',
    pattern: eFileQueen,
    mateIn: 5,
    difficulty: 'expert',
    rating: 1740,
    theme: ['queen', 'endurance'],
  }),
  puzzle({
    id: 'm5-knight-endurance',
    title: 'Knight Endurance',
    pattern: knightNet,
    mateIn: 5,
    difficulty: 'expert',
    rating: 1800,
    theme: ['knight mate', 'endurance'],
  }),

  puzzle({
    id: 'm6-rook-marathon',
    title: 'Rook Marathon',
    pattern: eFileRook,
    mateIn: 6,
    difficulty: 'master',
    rating: 1920,
    theme: ['back rank', 'long line'],
  }),
  puzzle({
    id: 'm7-queen-marathon',
    title: 'Queen Marathon',
    pattern: eFileQueen,
    mateIn: 7,
    difficulty: 'master',
    rating: 2050,
    theme: ['queen', 'long line'],
  }),
];

const candidatePuzzles = [
  {
    id: 'v2-001',
    title: 'Back Rank Switch',
    fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Re8#'],
    difficulty: 'starter',
    rating: 780,
    themes: ['back-rank', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'ladder'],
    source: 'manual-candidate',
    qualityNotes: [
      'Rush-friendly mate-in-1 with a direct file mate.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-002',
    title: 'Smothered Corner',
    fen: '6rk/6pp/8/6N1/8/8/6PP/6K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Nf7#'],
    difficulty: 'starter',
    rating: 840,
    themes: ['smothered-mate', 'knight-mate', 'corner-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'ladder'],
    source: 'manual-candidate',
    qualityNotes: [
      'Boxed king pattern with a knight mate instead of a major-piece finish.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-003',
    title: 'Diagonal Seal',
    fen: '7k/6pp/8/8/2B5/2B5/7P/5KR1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Bxg7#'],
    difficulty: 'easy',
    rating: 920,
    themes: ['bishop-diagonal', 'corner-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'ladder'],
    source: 'manual-candidate',
    qualityNotes: [
      'Bishop capture mates with rook support on the g-file.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-004',
    title: 'Knight Fork Mate',
    fen: '5rkr/5ppp/6N1/8/8/8/6PP/6K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Ne7#'],
    difficulty: 'easy',
    rating: 960,
    themes: ['knight-mate', 'corner-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'ladder'],
    source: 'manual-candidate',
    qualityNotes: [
      'Knight mate against a boxed king with occupied escape squares.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-005',
    title: 'Greek Gift Finish',
    fen: '5rk1/5ppp/8/6NQ/2B5/8/6PP/6K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Qxh7#'],
    difficulty: 'easy',
    rating: 1000,
    themes: ['queen-sacrifice', 'bishop-diagonal', 'knight-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'ladder'],
    source: 'manual-candidate',
    qualityNotes: [
      'Queen capture is protected by the knight and supported by the bishop.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-006',
    title: 'Deflect the Guard',
    fen: '5rk1/6pp/3N4/1B6/8/5Q2/6PP/4R1K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Qxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'medium',
    rating: 1120,
    themes: ['deflection', 'queen-sacrifice', 'rook-file', 'overloaded-defender'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'ladder'],
    source: 'manual-candidate',
    qualityNotes: [
      'Queen sacrifice deflects the king onto a rook-file mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-007',
    title: 'Black Deflection',
    fen: '4r1k1/6pp/5q2/8/1b6/3n4/6PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Qxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'medium',
    rating: 1140,
    themes: ['deflection', 'queen-sacrifice', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'ladder'],
    source: 'manual-candidate',
    qualityNotes: [
      'Black-to-move mirror adds orientation variety for Rush.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-008',
    title: 'File Clearance',
    fen: '5rk1/6pp/3N4/1B6/8/8/6PP/4RRK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Rxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'medium',
    rating: 1180,
    themes: ['rook-file', 'deflection'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'ladder'],
    source: 'manual-candidate',
    qualityNotes: [
      'Rook capture clears the final rook mate on the same file.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-009',
    title: 'Promote With Checkmate',
    fen: '5rk1/3P2pp/3N4/8/8/8/6PP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Rxf8+', 'Kxf8', 'd8=Q#'],
    difficulty: 'medium',
    rating: 1220,
    themes: ['promotion', 'deflection'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'ladder'],
    source: 'manual-candidate',
    qualityNotes: [
      'The rook decoy removes the promotion blocker before the queen mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-010',
    title: 'Black Promotion Net',
    fen: '5rk1/6pp/8/8/8/3n4/3p2PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Rxf1+', 'Kxf1', 'd1=Q#'],
    difficulty: 'medium',
    rating: 1240,
    themes: ['promotion', 'deflection'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'ladder'],
    source: 'manual-candidate',
    qualityNotes: [
      'Black-to-move promotion mate after a rook deflection.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-011',
    title: 'Black Back Rank Switch',
    fen: '4r1k1/5ppp/8/8/8/8/5PPP/6K1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 1,
    solution: ['Re1#'],
    difficulty: 'starter',
    rating: 820,
    themes: ['back-rank', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Black-to-move back-rank mate adds orientation variety for Blitz.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-012',
    title: 'Long Diagonal Seal',
    fen: '7k/6pp/8/8/2B5/2B5/7P/4K1R1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Bxg7#'],
    difficulty: 'starter',
    rating: 860,
    themes: ['bishop-diagonal', 'corner-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Bishop capture mates with rook support after the diagonal opens.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-013',
    title: 'Knight Clamp',
    fen: '6rk/6pp/8/6N1/8/8/5PPP/6K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Nf7#'],
    difficulty: 'starter',
    rating: 880,
    themes: ['knight-mate', 'corner-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Knight mate against a boxed king with extra own-piece blockers.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-014',
    title: 'Knight Interlock',
    fen: '5rkr/5ppp/6N1/8/8/8/6PP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Ne7#'],
    difficulty: 'easy',
    rating: 980,
    themes: ['knight-mate', 'pinned-defender', 'back-rank'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Knight finish uses occupied back-rank squares rather than a queen or rook mate.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-015',
    title: 'Queen Center File',
    fen: '6k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Qd8#'],
    difficulty: 'easy',
    rating: 990,
    themes: ['back-rank', 'center-board-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Central queen file mate varies the back-rank geometry.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-016',
    title: 'Black Queen Center File',
    fen: '3q2k1/5ppp/8/8/8/8/5PPP/6K1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 1,
    solution: ['Qd1#'],
    difficulty: 'easy',
    rating: 1010,
    themes: ['back-rank', 'center-board-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Black-to-move queen file mate mirrors central-file pressure.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-017',
    title: 'Black Knight Net',
    fen: '6k1/6pp/2b5/8/8/6nb/5P1P/6K1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 1,
    solution: ['Ne2#'],
    difficulty: 'easy',
    rating: 1040,
    themes: ['knight-mate', 'center-board-mate', 'pinned-defender'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Knight mate is supported by bishops covering the king escapes.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-018',
    title: 'Black Diagonal Lock',
    fen: '5kr1/8/2b5/8/8/8/4nPPP/7K b - - 0 1',
    sideToMove: 'black',
    mateIn: 1,
    solution: ['Bxg2#'],
    difficulty: 'easy',
    rating: 1060,
    themes: ['bishop-diagonal', 'pinned-defender'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Bishop capture mates because the knight covers the remaining escape.',
      'Validated with chess.js; needs engine review before approval.',
    ],
  },
  {
    id: 'v2-019',
    title: 'Queen Takes the Guard',
    fen: '5rk1/6pp/3N4/1B6/8/5Q2/P5PP/4R1K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Qxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'medium',
    rating: 1160,
    themes: ['deflection', 'queen-sacrifice', 'pinned-defender'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Queen sacrifice pulls the king onto the rook-file mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-020',
    title: 'Queen Decoy on the File',
    fen: '5rk1/p5pp/3N4/1B6/8/5Q2/6PP/4R1K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Qxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'medium',
    rating: 1180,
    themes: ['decoy', 'queen-sacrifice', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Decoy capture clears the final rook-file mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-021',
    title: 'Rook Clears the Guard',
    fen: '5rk1/6pp/3N4/1B6/8/8/P5PP/4RRK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Rxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'medium',
    rating: 1200,
    themes: ['decoy', 'rook-file', 'back-rank'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'First rook decoys the king so the second rook can mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-022',
    title: 'Rook File Deflection',
    fen: '5rk1/p5pp/3N4/1B6/8/8/6PP/4RRK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Rxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'medium',
    rating: 1210,
    themes: ['deflection', 'rook-file', 'pinned-defender'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Rook capture removes the back-rank guard before mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-023',
    title: 'Promotion After Deflection',
    fen: '5rk1/3P2pp/3N4/8/8/8/P5PP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Rxf8+', 'Kxf8', 'd8=Q#'],
    difficulty: 'medium',
    rating: 1240,
    themes: ['promotion', 'deflection', 'decoy'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Rook decoy clears the promotion square for the final queen mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-024',
    title: 'Promotion Tempo Net',
    fen: '5rk1/p2P2pp/3N4/8/8/8/6PP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Rxf8+', 'Kxf8', 'd8=Q#'],
    difficulty: 'medium',
    rating: 1260,
    themes: ['promotion', 'rook-file', 'decoy'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Promotion mate follows a rook-file decoy sequence.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-025',
    title: 'Black Queen Decoy',
    fen: '4r1k1/6pp/5q2/8/1b6/3n4/P5PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Qxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'medium',
    rating: 1280,
    themes: ['queen-sacrifice', 'decoy', 'rook-file', 'king-hunt'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Black queen sacrifice decoys the king onto a rook mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-026',
    title: 'Black Rook File Clearance',
    fen: '4rrk1/6pp/8/8/1b6/3n4/P5PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Rxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'medium',
    rating: 1300,
    themes: ['rook-file', 'decoy', 'back-rank', 'deflection'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'First rook clears the file for the second rook mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-027',
    title: 'Black Promotion After Decoy',
    fen: '5rk1/6pp/8/8/8/3n4/P2p2PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Rxf1+', 'Kxf1', 'd1=Q#'],
    difficulty: 'medium',
    rating: 1320,
    themes: ['promotion', 'deflection', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Black rook deflects the king before the promotion mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-028',
    title: 'Black Queen Pull',
    fen: '4r1k1/p5pp/5q2/8/1b6/3n4/6PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Qxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'medium',
    rating: 1340,
    themes: ['deflection', 'king-hunt', 'pinned-defender'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Queen pull drags the king onto the final rook-file mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-029',
    title: 'Quiet Decoy Build',
    fen: '5rk1/p5pp/3N4/1B6/8/5Q2/P5PP/4R1K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 3,
    solution: ['a3', 'a6', 'Qxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'advanced',
    rating: 1420,
    themes: ['king-hunt', 'deflection', 'discovered-check'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Longer candidate line introduces a quiet tempo before the decoy finish.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-030',
    title: 'Black Quiet Pull',
    fen: '4r1k1/p5pp/5q2/8/1b6/3n4/P5PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 3,
    solution: ['a6', 'a3', 'Qxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'advanced',
    rating: 1460,
    themes: ['double-check', 'decoy', 'king-hunt'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.1',
    qualityNotes: [
      'Black-to-move longer candidate line reaches the same decoy-to-mate structure.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-031',
    title: 'Center File Rook',
    fen: '6k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Rd8#'],
    difficulty: 'starter',
    rating: 820,
    themes: ['rook-file', 'center-board-mate', 'back-rank'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Rush v2.2 mate-in-1 candidate with a central rook-file finish.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-032',
    title: 'Black Center File Rook',
    fen: '3r2k1/5ppp/8/8/8/8/5PPP/6K1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 1,
    solution: ['Rd1#'],
    difficulty: 'starter',
    rating: 840,
    themes: ['rook-file', 'back-rank', 'center-board-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black-to-move mate-in-1 adds orientation variety to the rook-file pattern.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-033',
    title: 'A-File Queen Net',
    fen: '7k/6pp/8/8/8/8/6PP/Q5K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Qa8#'],
    difficulty: 'starter',
    rating: 860,
    themes: ['back-rank', 'queen-mate', 'corner-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Fast queen mate with a different file geometry from the earlier center-file examples.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-034',
    title: 'Black A-File Queen Net',
    fen: 'q5k1/6pp/8/8/8/8/6PP/7K b - - 0 1',
    sideToMove: 'black',
    mateIn: 1,
    solution: ['Qa1#'],
    difficulty: 'starter',
    rating: 880,
    themes: ['back-rank', 'queen-mate', 'corner-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black-to-move queen mate mirrors the a-file net for board-orientation practice.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-035',
    title: 'Gift on H7',
    fen: '5rk1/5ppp/8/6NQ/2B5/8/6PP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Qxh7#'],
    difficulty: 'easy',
    rating: 960,
    themes: ['sacrifice', 'bishop-diagonal', 'knight-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Queen capture finish uses bishop and knight support instead of a back-rank file.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-036',
    title: 'Knight Clamp Reloaded',
    fen: '6rk/6pp/8/6N1/8/8/5PPP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Nf7#'],
    difficulty: 'easy',
    rating: 980,
    themes: ['knight-mate', 'corner-mate', 'pinned-defender'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Knight mate against a boxed king with the rook pinning escape geometry.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-037',
    title: 'Back-Rank Knight Stitch',
    fen: '5rkr/5ppp/6N1/8/8/8/5PPP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Ne7#'],
    difficulty: 'easy',
    rating: 1000,
    themes: ['knight-mate', 'back-rank', 'pinned-defender'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Knight finish varies the back-rank motif without a queen or rook as the mating piece.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-038',
    title: 'Black Knight Closure',
    fen: '6k1/6pp/2b5/8/8/6nb/5P1P/6K1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 1,
    solution: ['Ne2#'],
    difficulty: 'easy',
    rating: 1020,
    themes: ['knight-mate', 'center-board-mate', 'bishop-diagonal'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black knight mate uses bishop coverage for the escape squares.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-039',
    title: 'Promotion Switch',
    fen: '6k1/3P1ppp/8/8/8/8/5PPP/6K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['d8=Q#'],
    difficulty: 'easy',
    rating: 1040,
    themes: ['promotion', 'back-rank', 'center-board-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Promotion mate adds a non-capture tactical finish to the Blitz pool.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-040',
    title: 'Black Promotion Switch',
    fen: '6k1/5ppp/8/8/8/8/3p1PPP/6K1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 1,
    solution: ['d1=Q#'],
    difficulty: 'easy',
    rating: 1060,
    themes: ['promotion', 'back-rank', 'center-board-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black-to-move promotion mate gives Rush another immediate promotion pattern.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-041',
    title: 'Queen Crossfire',
    fen: '6k1/6pp/8/7Q/8/8/6PP/6K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 1,
    solution: ['Qe8#'],
    difficulty: 'easy',
    rating: 1080,
    themes: ['center-board-mate', 'queen-mate', 'king-hunt'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Queen crossfire mates from the side rather than a corner-only setup.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-042',
    title: 'Black Queen Crossfire',
    fen: '6k1/6pp/8/8/7q/8/6PP/6K1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 1,
    solution: ['Qe1#'],
    difficulty: 'easy',
    rating: 1100,
    themes: ['center-board-mate', 'queen-mate', 'king-hunt'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black queen crossfire mirrors the side-rank finish for color variety.',
      'Validated with chess.js; needs engine/source review before approval.',
    ],
  },
  {
    id: 'v2-043',
    title: 'Queen Guard Decoy',
    fen: '5rk1/1p4pp/3N4/1B6/8/5Q2/P5PP/4R1K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Qxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'medium',
    rating: 1180,
    themes: ['deflection', 'queen-sacrifice', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Queen sacrifice deflects the guard into a rook-file mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-044',
    title: 'Overloaded Rook Guard',
    fen: '5rk1/2p3pp/3N4/1B6/8/5Q2/1P4PP/4R1K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Qxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'medium',
    rating: 1200,
    themes: ['overloaded-defender', 'decoy', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'The queen decoy overloads the king-side guard before the rook mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-045',
    title: 'First Rook Drag',
    fen: '5rk1/1p4pp/3N4/1B6/8/8/P5PP/4RRK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Rxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'medium',
    rating: 1220,
    themes: ['deflection', 'rook-file', 'back-rank'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'First rook clears and drags the king for the second rook mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-046',
    title: 'Pinned Rook Clearance',
    fen: '5rk1/2p3pp/3N4/1B6/8/8/1P4PP/4RRK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Rxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'medium',
    rating: 1240,
    themes: ['pinned-defender', 'rook-file', 'decoy'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Rook-file clearance keeps the solution short while varying the defender tags.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-047',
    title: 'Promotion Gate',
    fen: '5rk1/2pP2pp/3N4/8/8/8/1P4PP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Rxf8+', 'Kxf8', 'd8=Q#'],
    difficulty: 'medium',
    rating: 1260,
    themes: ['promotion', 'deflection', 'decoy'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Rook decoy clears the promotion square for a queen mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-048',
    title: 'Promotion File Drag',
    fen: '5rk1/1p1P2pp/3N4/8/8/8/P5PP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Rxf8+', 'Kxf8', 'd8=Q#'],
    difficulty: 'medium',
    rating: 1280,
    themes: ['promotion', 'rook-file', 'overloaded-defender'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Promotion finish follows a file deflection pattern with different support pieces.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-049',
    title: 'Black Queen Decoy II',
    fen: '4r1k1/1p4pp/5q2/8/1b6/3n4/P5PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Qxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'medium',
    rating: 1300,
    themes: ['queen-sacrifice', 'decoy', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black queen sacrifice pulls the king into a rook-file mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-050',
    title: 'Black Overload Pull',
    fen: '4r1k1/2p3pp/5q2/8/1b6/3n4/1P4PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Qxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'medium',
    rating: 1320,
    themes: ['overloaded-defender', 'deflection', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black-to-move overload pattern adds another quick Rush deflection.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-051',
    title: 'Black Rook Drag',
    fen: '4rrk1/1p4pp/8/8/1b6/3n4/P5PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Rxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'medium',
    rating: 1340,
    themes: ['rook-file', 'decoy', 'back-rank'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'First rook decoys the king so the second rook can mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-052',
    title: 'Black File Clearance',
    fen: '4rrk1/2p3pp/8/8/1b6/3n4/1P4PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Rxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'medium',
    rating: 1360,
    themes: ['pinned-defender', 'rook-file', 'deflection'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black rook clearance keeps the mating pattern compact for Rush.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-053',
    title: 'Black Promotion Gate',
    fen: '5rk1/1p4pp/8/8/8/3n4/P2p2PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Rxf1+', 'Kxf1', 'd1=Q#'],
    difficulty: 'medium',
    rating: 1380,
    themes: ['promotion', 'deflection', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black decoys the king before the promotion mate.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-054',
    title: 'Black Promotion Pull',
    fen: '5rk1/2p3pp/8/8/8/3n4/1P1p2PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Rxf1+', 'Kxf1', 'd1=Q#'],
    difficulty: 'medium',
    rating: 1400,
    themes: ['promotion', 'decoy', 'overloaded-defender'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Promotion mate after a king pull adds another non-rook final move.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-055',
    title: 'Diagonal Queen Check',
    fen: '4k3/2p3R1/4p3/7p/2P5/1B5Q/K7/7N w - - 0 1',
    sideToMove: 'white',
    mateIn: 2,
    solution: ['Qxe6+', 'Kd8', 'Rg8#'],
    difficulty: 'medium',
    rating: 1420,
    themes: ['bishop-diagonal', 'king-hunt', 'queen-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Queen check drives the king into a rook mate with bishop support.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-056',
    title: 'Black Diagonal Queen Check',
    fen: '7n/k7/1b5q/2p5/7P/4P3/2P3r1/4K3 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Qxh4+', 'Kd1', 'Qh1#'],
    difficulty: 'medium',
    rating: 1440,
    themes: ['bishop-diagonal', 'king-hunt', 'queen-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black queen check creates a short king-hunt finish on the h-file.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-057',
    title: 'Black Pull on F1',
    fen: '4r1k1/3p2pp/5q2/8/1b6/3n4/6PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 2,
    solution: ['Qxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'medium',
    rating: 1460,
    themes: ['deflection', 'pinned-defender', 'king-hunt'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Queen pull turns the pinned defender motif into a short mating sequence.',
      'Validated with chess.js and checked for no immediate mate-in-1.',
    ],
  },
  {
    id: 'v2-058',
    title: 'Quiet Queen Decoy',
    fen: '5rk1/1p4pp/3N4/1B6/8/5Q2/P5PP/4R1K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 3,
    solution: ['a3', 'b6', 'Qxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'advanced',
    rating: 1500,
    themes: ['deflection', 'quiet-move', 'queen-sacrifice'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Deeper Rush candidate line is legal and validator-clean.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-059',
    title: 'Overload Before Decoy',
    fen: '5rk1/2p3pp/3N4/1B6/8/5Q2/1P4PP/4R1K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 3,
    solution: ['b3', 'c6', 'Qxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'advanced',
    rating: 1520,
    themes: ['overloaded-defender', 'quiet-move', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Adds a short preparatory pair before the decoy-to-mate line.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-060',
    title: 'Rook Drag Build',
    fen: '5rk1/1p4pp/3N4/1B6/8/8/P5PP/4RRK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 3,
    solution: ['a3', 'b6', 'Rxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'advanced',
    rating: 1540,
    themes: ['rook-file', 'decoy', 'calculation'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Rook-file candidate extends the calculation length for Classic and Survival.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-061',
    title: 'Clearance Build',
    fen: '5rk1/2p3pp/3N4/1B6/8/8/1P4PP/4RRK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 3,
    solution: ['b3', 'c6', 'Rxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'advanced',
    rating: 1560,
    themes: ['pinned-defender', 'rook-file', 'calculation'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Clearance pattern gives the deeper pool another rook-file calculation line.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-062',
    title: 'Promotion Prep',
    fen: '5rk1/2pP2pp/3N4/8/8/8/1P4PP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 3,
    solution: ['b3', 'c6', 'Rxf8+', 'Kxf8', 'd8=Q#'],
    difficulty: 'advanced',
    rating: 1580,
    themes: ['promotion', 'quiet-move', 'deflection'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Promotion finish extends beyond the instant Rush solve layer.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-063',
    title: 'Promotion Lift',
    fen: '5rk1/1p1P2pp/3N4/8/8/8/P5PP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 3,
    solution: ['a3', 'b6', 'Rxf8+', 'Kxf8', 'd8=Q#'],
    difficulty: 'advanced',
    rating: 1600,
    themes: ['promotion', 'overloaded-defender', 'calculation'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Promotion candidate adds a longer calculation path to the v2.2 set.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-064',
    title: 'Black Quiet Decoy',
    fen: '4r1k1/1p4pp/5q2/8/1b6/3n4/P5PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 3,
    solution: ['b6', 'a3', 'Qxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'advanced',
    rating: 1620,
    themes: ['queen-sacrifice', 'quiet-move', 'decoy'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black-to-move deeper line keeps orientation variety in mate-in-3 content.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-065',
    title: 'Black Overload Prep',
    fen: '4r1k1/2p3pp/5q2/8/1b6/3n4/1P4PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 3,
    solution: ['c6', 'b3', 'Qxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'advanced',
    rating: 1640,
    themes: ['overloaded-defender', 'quiet-move', 'deflection'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black overload prep gives Survival another longer forcing-line candidate.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-066',
    title: 'Black Rook Drag Build',
    fen: '4rrk1/1p4pp/8/8/1b6/3n4/P5PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 3,
    solution: ['b6', 'a3', 'Rxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'advanced',
    rating: 1660,
    themes: ['rook-file', 'decoy', 'calculation'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black rook-file candidate mirrors the longer drag pattern.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-067',
    title: 'Black Promotion Prep',
    fen: '5rk1/1p4pp/8/8/8/3n4/P2p2PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 3,
    solution: ['b6', 'a3', 'Rxf1+', 'Kxf1', 'd1=Q#'],
    difficulty: 'advanced',
    rating: 1680,
    themes: ['promotion', 'quiet-move', 'rook-file'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black promotion line extends the non-rook final mate pattern.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-068',
    title: 'Bishop Chase Check',
    fen: '4k3/2p3R1/4p3/7p/2P5/1B5Q/K7/7N w - - 0 1',
    sideToMove: 'white',
    mateIn: 3,
    solution: ['c5', 'h4', 'Qxe6+', 'Kd8', 'Rg8#'],
    difficulty: 'advanced',
    rating: 1700,
    themes: ['bishop-diagonal', 'king-hunt', 'discovered-check'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'King-hunt candidate includes a diagonal queen check before the mate.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-069',
    title: 'Black Corner Chase',
    fen: '7n/k7/1b5q/2p5/7P/4P3/2P3r1/4K3 b - - 0 1',
    sideToMove: 'black',
    mateIn: 3,
    solution: ['c4', 'e4', 'Qxh4+', 'Kd1', 'Qh1#'],
    difficulty: 'advanced',
    rating: 1720,
    themes: ['king-hunt', 'double-check', 'queen-mate'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black queen chase gives the candidate pool a less back-rank-driven sequence.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-070',
    title: 'Black Pull Prep',
    fen: '4r1k1/3p2pp/5q2/8/1b6/3n4/6PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 3,
    solution: ['d6', 'h3', 'Qxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'advanced',
    rating: 1740,
    themes: ['pinned-defender', 'deflection', 'quiet-move'],
    contentStatus: 'candidate',
    modeFit: ['rush', 'blitz', 'classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Pinned-defender candidate sets up a queen pull into the final rook mate.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-071',
    title: 'Long Queen Deflection',
    fen: '5rk1/1p4pp/3N4/1B6/8/5Q2/P5PP/4R1K1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 4,
    solution: ['a3', 'b6', 'h3', 'h6', 'Qxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'expert',
    rating: 1820,
    themes: ['deflection', 'calculation', 'queen-sacrifice'],
    contentStatus: 'candidate',
    modeFit: ['classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Classic/Survival candidate for testing longer Rush sequences.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-072',
    title: 'Long Rook Clearance',
    fen: '5rk1/2p3pp/3N4/1B6/8/8/1P4PP/4RRK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 4,
    solution: ['b3', 'c6', 'h3', 'h6', 'Rxf8+', 'Kxf8', 'Re8#'],
    difficulty: 'expert',
    rating: 1860,
    themes: ['rook-file', 'calculation', 'pinned-defender'],
    contentStatus: 'candidate',
    modeFit: ['classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Mate-in-4 candidate is scoped to Classic, Survival, and Ladder rather than Blitz.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-073',
    title: 'Long Promotion Net',
    fen: '5rk1/2pP2pp/3N4/8/8/8/1P4PP/5RK1 w - - 0 1',
    sideToMove: 'white',
    mateIn: 4,
    solution: ['b3', 'c6', 'h3', 'h6', 'Rxf8+', 'Kxf8', 'd8=Q#'],
    difficulty: 'expert',
    rating: 1900,
    themes: ['promotion', 'calculation', 'decoy'],
    contentStatus: 'candidate',
    modeFit: ['classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Longer promotion candidate supports Survival scaling into deeper mate content.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-074',
    title: 'Black Long Queen Pull',
    fen: '4r1k1/1p4pp/5q2/8/1b6/3n4/P5PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 4,
    solution: ['b6', 'a3', 'h6', 'h3', 'Qxf1+', 'Kxf1', 'Re1#'],
    difficulty: 'expert',
    rating: 1940,
    themes: ['queen-sacrifice', 'calculation', 'king-hunt'],
    contentStatus: 'candidate',
    modeFit: ['classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black-to-move mate-in-4 candidate broadens deeper Rush orientation.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
  {
    id: 'v2-075',
    title: 'Black Long Promotion Net',
    fen: '5rk1/1p4pp/8/8/8/3n4/P2p2PP/5RK1 b - - 0 1',
    sideToMove: 'black',
    mateIn: 4,
    solution: ['b6', 'a3', 'h6', 'h3', 'Rxf1+', 'Kxf1', 'd1=Q#'],
    difficulty: 'expert',
    rating: 1980,
    themes: ['promotion', 'calculation', 'overloaded-defender'],
    contentStatus: 'candidate',
    modeFit: ['classic', 'survival', 'ladder'],
    source: 'manual-candidate-v2.2',
    qualityNotes: [
      'Black promotion mate-in-4 candidate is reserved for Classic and Survival depth.',
      'Exact mate-depth and practical forcing quality require engine review before approval.',
    ],
  },
];

export const puzzles = [...devPuzzles, ...candidatePuzzles];
